import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const evolventa = localFont({
  src: [
    { path: "./fonts/Evolventa-Regular.woff", style: "normal", weight: "400" },
    { path: "./fonts/Evolventa-Bold.woff", style: "bold", weight: "700" },
    { path: "./fonts/Evolventa-Oblique.woff", style: "italic", weight: "400" },
    {
      path: "./fonts/Evolventa-BoldOblique.woff",
      style: "italic",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={evolventa.className}>{children}</body>
    </html>
  );
}
